// Copyright (C) 2026 Fiber
//
// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at https://mozilla.org/MPL/2.0/.
//
// What you may do:
// - Use this software for any purpose, including commercially, and build and
//   sell your own products on top of it.
// - Change it, and create new works based on it.
// - Distribute copies of it, with or without your changes.
// - Combine it with files under any other licence, proprietary ones included,
//   and licence that larger work on your own terms.
//
// What you must do in return:
// - Keep this notice on every file you received it on.
// - Publish, under these same terms, the source of every file covered by them
//   that you distribute, including the ones you changed, so that whoever
//   receives your version can obtain that source.
// - Leave Fiber out of it: the name "Fiber", its branding, its logos and its
//   trademarks may not be used to endorse or promote what you build, and this
//   licence grants no right to them.
//
// Disclaimer:
// AS FAR AS THE LAW ALLOWS, THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
// OR CONDITION OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
// NON-INFRINGEMENT. IN NO EVENT SHALL FIBER BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT
// LIMITED TO LOSS OF USE, DATA, PROFITS, OR BUSINESS INTERRUPTION) ARISING OUT
// OF OR RELATED TO THESE TERMS OR THE USE OR NATURE OF THE SOFTWARE, UNDER ANY
// KIND OF LEGAL CLAIM.
//
// This header is a summary written for convenience. Where it differs from the
// LICENSE file, the LICENSE file governs.

syntax = "proto3";

package scribe.clients.recommendation.v1;

import "scribe/protocol/common.proto";

message User {
  string id = 1;
  scribe.v1.Json labels = 2;
  string comment = 3;
}

message Item {
  string id = 1;
  scribe.v1.Json labels = 2;
  string comment = 3;
  repeated string categories = 4;
  bool is_hidden = 5;
  string timestamp = 6;
}

message Feedback {
  string type = 1;
  string user_id = 2;
  string item_id = 3;
  double value = 4;
  string timestamp = 5;
}

message UpsertUserRequest {
  User user = 1;
}

message UpsertItemRequest {
  Item item = 1;
}

message DeleteUserRequest {
  string user_id = 1;
}

message DeleteItemRequest {
  string item_id = 1;
}

message InsertFeedbackRequest {
  repeated Feedback feedback = 1;
}

message RecommendRequest {
  string user_id = 1;
  uint32 count = 2;
  string category = 3;
  uint32 offset = 4;
}

message RecommendResult {
  repeated string item_ids = 1;
  scribe.v1.Failure error = 2;
}

message VoidResult {
  scribe.v1.Failure error = 1;
}

service Recommendation {
  rpc UpsertUser(UpsertUserRequest) returns (VoidResult);
  rpc UpsertItem(UpsertItemRequest) returns (VoidResult);
  rpc DeleteUser(DeleteUserRequest) returns (VoidResult);
  rpc DeleteItem(DeleteItemRequest) returns (VoidResult);
  rpc InsertFeedback(InsertFeedbackRequest) returns (VoidResult);
  rpc Recommend(RecommendRequest) returns (RecommendResult);
}
