version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "[CHORE]:"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /sdk/js
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "[CHORE]:"
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /sdk/dart
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "[CHORE]:"
    open-pull-requests-limit: 5
