services:
  vector:
    container_name: "supabase-vector"
    image: "timberio/vector:0.53.0-alpine"
    restart: "unless-stopped"
    volumes:
      - "{{sdk_root}}/ops/logs/vector.yml:/etc/vector/vector.yml:ro,z"
      - "/var/run/docker.sock:/var/run/docker.sock:ro,z"
    environment:
      LOGFLARE_PUBLIC_ACCESS_TOKEN: ${LOGFLARE_PUBLIC_ACCESS_TOKEN}
    command: ["--config", "/etc/vector/vector.yml"]
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://vector:9001/health",
        ]
      interval: "5s"
      timeout: "5s"
      retries: 3
    security_opt:
      - "label=disable"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  analytics:
    profiles: ["ops"]
    container_name: "supabase-analytics"
    image: "supabase/logflare:1.36.1"
    restart: "unless-stopped"
    environment:
      LOGFLARE_NODE_HOST: "127.0.0.1"
      DB_USERNAME: "supabase_admin"
      DB_DATABASE: "_supabase"
      DB_HOSTNAME: "db"
      DB_PORT: "5432"
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: "_analytics"
      LOGFLARE_PUBLIC_ACCESS_TOKEN: ${LOGFLARE_PUBLIC_ACCESS_TOKEN}
      LOGFLARE_PRIVATE_ACCESS_TOKEN: ${LOGFLARE_PRIVATE_ACCESS_TOKEN}
      LOGFLARE_SINGLE_TENANT: "true"
      LOGFLARE_SUPABASE_MODE: "true"
      POSTGRES_BACKEND_URL: "postgresql://supabase_admin:${POSTGRES_PASSWORD}@db:5432/_supabase"
      POSTGRES_BACKEND_SCHEMA: "_analytics"
      LOGFLARE_FEATURE_FLAG_OVERRIDE: "multibackend=true"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4000/health"]
      interval: "5s"
      timeout: "5s"
      retries: 10
    depends_on:
      db:
        condition: "service_healthy"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
