name: devops
title: Dynamic links and remote configuration.
optional: true

requires: []

ops:
  services: []
  profile: null
  gateway: []
  env: []

sql: null
protocol: protocol/devops.proto
export: ./features

routes: []
