name: "{{app_name_snake}}"

services:
  studio:
    cpu_shares: 512
    deploy:
      resources:
        limits:
          cpus: "{{studio_cpu_limit}}"
          memory: "{{studio_mem_limit}}"
        reservations:
          memory: "{{studio_mem_res}}"

  caddy:
    cpu_shares: 2048
    deploy:
      resources:
        limits:
          memory: "{{caddy_mem_limit}}"
        reservations:
          memory: "{{caddy_mem_res}}"

  kong:
    cpu_shares: 2048
    deploy:
      resources:
        limits:
          memory: "{{kong_mem_limit}}"
        reservations:
          memory: "{{kong_mem_res}}"


  rest:
    cpu_shares: {{rest_cpu_shares}}
    deploy:
      resources:
        limits:
          memory: "{{rest_mem_limit}}"
        reservations:
          memory: "{{rest_mem_res}}"




  db-migrate:
    deploy:
      resources:
        limits:
          memory: "{{db_migrate_mem_limit}}"


  meta:
    cpu_shares: 1024
    deploy:
      resources:
        limits:
          memory: "{{meta_mem_limit}}"
        reservations:
          memory: "{{meta_mem_res}}"

  functions:
    cpu_shares: 1024
    deploy:
      resources:
        limits:
          memory: "{{functions_mem_limit}}"
        reservations:
          memory: "{{functions_mem_res}}"

  api:
    cpu_shares: {{api_cpu_shares}}
    deploy:
      resources:
        limits:
          memory: "{{api_mem_limit}}"
        reservations:
          memory: "{{api_mem_res}}"


  db:
    cpu_shares: 4096
    deploy:
      resources:
        limits:
          memory: "{{db_mem_limit}}"
        reservations:
          memory: "{{db_mem_res}}"


  supavisor:
    cpu_shares: 1024
    deploy:
      resources:
        limits:
          memory: "{{supavisor_mem_limit}}"
        reservations:
          memory: "{{supavisor_mem_res}}"

  nats:
    cpu_shares: 1024
    deploy:
      resources:
        limits:
          memory: "{{nats_mem_limit}}"
        reservations:
          memory: "{{nats_mem_res}}"

  redis:
    cpu_shares: 2048
    deploy:
      resources:
        limits:
          memory: "{{redis_mem_limit}}"
        reservations:
          memory: "{{redis_mem_res}}"




