// Copyright (C) 2026 Fiber
//
// This file is part of scribe and is made available under the PolyForm Shield
// License 1.0.0. The full terms are in the LICENSE file at the root of this
// repository, and at https://polyformproject.org/licenses/shield/1.0.0
//
// What you may do:
// - Use this software for any purpose, including commercially, and build and
//   sell your own products on top of it.
// - Change it, and create new works based on it.
// - Distribute copies of it, with or without your changes.
//
// The one thing you may not do:
// - Use it to provide any product that competes with scribe, or with any
//   product Fiber or its affiliates provide using scribe. Products compete
//   even when they are offered free of charge, through a different kind of
//   interface, or for a different technical platform.
//
// If you pass this software on:
// - Anyone who receives any part of it from you must also receive these terms,
//   or the URL above, together with the "Required Notice" line carried by the
//   LICENSE file.
//
// Disclaimer:
// AS FAR AS THE LAW ALLOWS, THIS SOFTWARE COMES AS IS, WITHOUT ANY WARRANTY OR
// CONDITION, AND THE LICENSOR WILL NOT BE LIABLE TO YOU FOR ANY DAMAGES ARISING
// OUT OF THESE TERMS OR THE USE OR NATURE OF THE SOFTWARE, UNDER ANY KIND OF
// LEGAL CLAIM.
//
// This header is a summary written for convenience. Where it differs from the
// LICENSE file, the LICENSE file governs.

import { assertEquals, assert } from "@std/assert";
import { PROTOCOL_VERSION } from "../mod.ts";
import { Registration } from "../gen/scribe/protocol/manifest_pb.ts";
import { Worker as WorkerService } from "../gen/scribe/protocol/invocation_pb.ts";
import { QueueDispatch } from "../gen/scribe/host/packages/foundation/event_driven/queue/protocol/queue_pb.ts";
import { HookDispatch } from "../gen/scribe/host/packages/foundation/event_driven/hook/protocol/hook_pb.ts";
import { CronDispatch } from "../gen/scribe/host/packages/foundation/event_driven/cron/protocol/cron_pb.ts";
import { LogDispatch } from "../gen/scribe/protocol/logs_pb.ts";
import { procedurePath } from "../src/transport/wire.ts";

const sdkRoot = new URL("../", import.meta.url);

const scribeRoot = new URL("../../../", import.meta.url);

async function protoFiles(): Promise<string[]> {
  const found: string[] = [];

  async function walk(directory: URL): Promise<void> {
    for await (const entry of Deno.readDir(directory)) {
      const child = new URL(`${entry.name}${entry.isDirectory ? "/" : ""}`, directory);
      if (entry.isDirectory) {
        if (entry.name === "sdk" || entry.name === "node_modules") continue;
        await walk(child);
        continue;
      }
      if (entry.name.endsWith(".proto")) found.push(child.pathname);
    }
  }

  await walk(scribeRoot);
  return found;
}

Deno.test("the SDK announces the protocol version the contract carries", async () => {
  const declared = (await Deno.readTextFile(new URL("protocol/VERSION", scribeRoot))).trim();

  assertEquals(PROTOCOL_VERSION, declared);
});

Deno.test("every .proto of the contract has its generated stub in the SDK", async () => {
  const missing: string[] = [];

  for (const proto of await protoFiles()) {
    const relative = `scribe/${proto.slice(scribeRoot.pathname.length)}`.replace(/\.proto$/, "_pb.ts");
    const stub = new URL(`gen/${relative}`, sdkRoot);
    try {
      await Deno.stat(stub);
    } catch {
      missing.push(relative);
    }
  }

  assertEquals(missing, [], "run `koko-kernel gen proto` to regenerate the stubs");
});

Deno.test("the procedure paths a foreign SDK must implement are stable", () => {
  assertEquals(procedurePath(Registration.method.describe), "/scribe.v1.Registration/Describe");
  assertEquals(procedurePath(WorkerService.method.invoke), "/scribe.v1.Worker/Invoke");
  assertEquals(
    procedurePath(QueueDispatch.method.handle),
    "/scribe.runtime.queue.v1.QueueDispatch/Handle",
  );
  assertEquals(
    procedurePath(HookDispatch.method.handle),
    "/scribe.runtime.hook.v1.HookDispatch/Handle",
  );
  assertEquals(
    procedurePath(CronDispatch.method.trigger),
    "/scribe.runtime.cron.v1.CronDispatch/Trigger",
  );
  assertEquals(procedurePath(LogDispatch.method.handle), "/scribe.v1.LogDispatch/Handle");
});

Deno.test("the generated stubs are versioned, not gitignored", async () => {
  const stub = new URL("gen/scribe/protocol/manifest_pb.ts", sdkRoot);
  const source = await Deno.readTextFile(stub);

  assert(source.includes("@generated by protoc-gen-es"));
});
