// Copyright (C) 2026 Fiber
//
// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at https://mozilla.org/MPL/2.0/.
//
// What you may do:
// - Use this software for any purpose, including commercially, and build and
//   sell your own products on top of it.
// - Change it, and create new works based on it.
// - Distribute copies of it, with or without your changes.
// - Combine it with files under any other licence, proprietary ones included,
//   and licence that larger work on your own terms.
//
// What you must do in return:
// - Keep this notice on every file you received it on.
// - Publish, under these same terms, the source of every file covered by them
//   that you distribute, including the ones you changed, so that whoever
//   receives your version can obtain that source.
// - Leave Fiber out of it: the name "Fiber", its branding, its logos and its
//   trademarks may not be used to endorse or promote what you build, and this
//   licence grants no right to them.
//
// Disclaimer:
// AS FAR AS THE LAW ALLOWS, THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
// OR CONDITION OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
// NON-INFRINGEMENT. IN NO EVENT SHALL FIBER BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT
// LIMITED TO LOSS OF USE, DATA, PROFITS, OR BUSINESS INTERRUPTION) ARISING OUT
// OF OR RELATED TO THESE TERMS OR THE USE OR NATURE OF THE SOFTWARE, UNDER ANY
// KIND OF LEGAL CLAIM.
//
// This header is a summary written for convenience. Where it differs from the
// LICENSE file, the LICENSE file governs.

import { assertEquals, assert } from "@std/assert";
import { PROTOCOL_VERSION } from "../mod.ts";
import { Registration } from "../gen/scribe/protocol/manifest_pb.ts";
import { Worker as WorkerService } from "../gen/scribe/protocol/invocation_pb.ts";
import { QueueDispatch } from "../gen/scribe/host/pkg/packages/foundation/protocol/queue/queue_pb.ts";
import { HookDispatch } from "../gen/scribe/host/pkg/packages/foundation/protocol/hook/hook_pb.ts";
import { CronDispatch } from "../gen/scribe/host/pkg/packages/foundation/protocol/cron/cron_pb.ts";
import { LogDispatch } from "../gen/scribe/protocol/logs_pb.ts";
import { procedurePath } from "../src/transport/wire.ts";

const sdkRoot = new URL("../", import.meta.url);

const scribeRoot = new URL("../../../", import.meta.url);

async function protoFiles(): Promise<string[]> {
  const found: string[] = [];

  async function walk(directory: URL): Promise<void> {
    for await (const entry of Deno.readDir(directory)) {
      const child = new URL(`${entry.name}${entry.isDirectory ? "/" : ""}`, directory);
      if (entry.isDirectory) {
        if (entry.name === "sdk" || entry.name === "node_modules") continue;
        await walk(child);
        continue;
      }
      if (entry.name.endsWith(".proto")) found.push(child.pathname);
    }
  }

  await walk(scribeRoot);
  return found;
}

Deno.test("the SDK announces the protocol version the contract carries", async () => {
  const declared = (await Deno.readTextFile(new URL("protocol/VERSION", scribeRoot))).trim();

  assertEquals(PROTOCOL_VERSION, declared);
});

Deno.test("every .proto of the contract has its generated stub in the SDK", async () => {
  const missing: string[] = [];

  for (const proto of await protoFiles()) {
    const relative = `scribe/${proto.slice(scribeRoot.pathname.length)}`.replace(/\.proto$/, "_pb.ts");
    const stub = new URL(`gen/${relative}`, sdkRoot);
    try {
      await Deno.stat(stub);
    } catch {
      missing.push(relative);
    }
  }

  assertEquals(missing, [], "run `koko-kernel gen proto` to regenerate the stubs");
});

Deno.test("the procedure paths a foreign SDK must implement are stable", () => {
  assertEquals(procedurePath(Registration.method.describe), "/scribe.v1.Registration/Describe");
  assertEquals(procedurePath(WorkerService.method.invoke), "/scribe.v1.Worker/Invoke");
  assertEquals(
    procedurePath(QueueDispatch.method.handle),
    "/scribe.runtime.queue.v1.QueueDispatch/Handle",
  );
  assertEquals(
    procedurePath(HookDispatch.method.handle),
    "/scribe.runtime.hook.v1.HookDispatch/Handle",
  );
  assertEquals(
    procedurePath(CronDispatch.method.trigger),
    "/scribe.runtime.cron.v1.CronDispatch/Trigger",
  );
  assertEquals(procedurePath(LogDispatch.method.handle), "/scribe.v1.LogDispatch/Handle");
});

Deno.test("the generated stubs are versioned, not gitignored", async () => {
  const stub = new URL("gen/scribe/protocol/manifest_pb.ts", sdkRoot);
  const source = await Deno.readTextFile(stub);

  assert(source.includes("@generated by protoc-gen-es"));
});
